plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - course_modules_2025/AccessingDataAndQC/AccessingDataAndQC.md
  - course_modules_2025/Alignment_&_VariantCalling/AlignmentAndVariantCalling.md
  - course_modules_2025/DetectingResistance/DetectingResistance.md
  - course_modules_2025/GenomeAssemblyAndAnnotation/GenomeAssemblyAndAnnotation.md
  - course_modules_2025/PhylogeneticAnalysis/PhylogeneticAnalysis.md
  - course_modules_2025/PhylogeneticVisualization/PhylogeneticVisualization.md
  - course_modules_2025/EnvironmentAndCommandLine.md
